apiVersion: app/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: deploy1

spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod1
  template:
    metadata:
      name: my-pod-error
      labels:
        app: pod1
    spec:
      containers:
      - name: container1
        image: img-name
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-apache

spec:
  selector:
    apps: pod1
  type: NodePort
  ports:
   - targetPort: 80
     port: 80
     nodePort: 30000
